# Generated by Django 5.2 on 2026-01-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_display', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pembeli', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('total_harga', models.FloatField(blank=True, db_column='totalHarga', null=True)),
            ],
            options={
                'db_table': 'Transaksi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('subtotal_harga', models.FloatField(blank=True, db_column='subtotalHarga', null=True)),
                ('id_barang', models.ForeignKey(blank=True, db_column='id_barang', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu_display.barang')),
                ('id_transaksi', models.ForeignKey(blank=True, db_column='id_transaksi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu_display.transaksi')),
            ],
        ),
    ]
